import sys
import os
import json
from pathlib import Path
import datetime

# Paths
PROJECT_ROOT = Path(__file__).resolve().parent.parent
sys.path.append(str(PROJECT_ROOT / "src"))

# Load .env
env_path = PROJECT_ROOT / ".env"
if env_path.exists():
    with open(env_path, "r", encoding="utf-8") as f:
        for line in f:
            if "=" in line and not line.startswith("#"):
                parts = line.strip().split("=", 1)
                if len(parts) == 2:
                    key, value = parts
                    os.environ[key] = value.strip("'\"")

# Infrastructure imports
from llm import LLMGateway, GatewayModelClient, RetryPolicy
from llm.providers import OpenAICompatibleProvider

KNOWLEDGE_DIR = PROJECT_ROOT / "factor_library" / "raw" / "negative_knowledge"
FAILURES_FILE = PROJECT_ROOT / "factor_library" / "raw" / "evolved" / "evolution_failures.jsonl"
LESSONS_FILE = PROJECT_ROOT / "factor_library" / "raw" / "evolved" / "distilled_lessons_evolution.md"

def distill_evolution_knowledge():
    if not FAILURES_FILE.exists():
        print("No evolution failures recorded yet.")
        return

    failures = []
    with open(FAILURES_FILE, "r", encoding="utf-8") as f:
        for line in f:
            try:
                failures.append(json.loads(line))
            except: continue

    if not failures:
        print("Evolution failures file is empty.")
        return

    # 抽取最近的 50 条记录
    recent_failures = failures[-50:]
    
    # Prepare context
    failure_context = ""
    for f in recent_failures:
        failure_context += f"- Type: {f.get('type')}, Reason: {f.get('reason')}, Expr: {f.get('expression')}, Parents: {f.get('parents')}\n"

    # LLM Setup
    api_key = os.getenv("OPENAI_API_KEY")
    model_name = os.getenv("LLM_MODEL", "gpt-4-turbo")
    base_url = os.getenv("OPENAI_BASE_URL")
    
    if not api_key:
        print("Error: OPENAI_API_KEY not found.")
        return

    provider = OpenAICompatibleProvider(api_key=api_key, base_url=base_url)
    gateway = LLMGateway(provider=provider, retry_policy=RetryPolicy(), default_model=model_name)
    client = GatewayModelClient(gateway)

    system_prompt = """You are a senior Quantitative Strategist specializing in Genetic Programming and Evolutionary Algorithms.
Your task is to analyze a list of EVOLUTION failures (factors generated by crossover/mutation that failed validation).
Identify patterns where specific recombinations of operators or parents consistently lead to Look-ahead bias or Overfitting.
Distill these into 3-5 actionable lessons for the evolution engine.
Format as a clean Markdown document."""

    user_prompt = f"Here are the recent 50 evolution failures:\n\n{failure_context}\n\nPlease provide the distilled evolution lessons in Markdown."

    print("Distilling evolution knowledge...")
    try:
        distilled_text = client.generate(system_prompt=system_prompt, user_prompt=user_prompt)
        
        with open(LESSONS_FILE, "w", encoding="utf-8") as f:
            now_str = datetime.datetime.now().strftime("%Y-%m-%d %H:%M:%S")
            f.write(f"# 因子演化负面知识库 (Distilled Evolution Lessons)\n\n")
            f.write(f"> 上次更新时间: {now_str}\n\n")
            f.write(distilled_text)
        
        print(f"Successfully updated {LESSONS_FILE}")
    except Exception as e:
        print(f"Distillation failed: {e}")

if __name__ == "__main__":
    distill_evolution_knowledge()
